
MODULE RANDOM_MOD
IMPLICIT NONE
SAVE

INTEGER*4, DIMENSION(20,12) :: RANDOMSTATUS ! Size: number of random number streams, size of seed array
INTEGER*4 RANDOMSEED/123456789/ !randomnumber seed
INTEGER*4 RANSEED_SEQ/1/           !index of random number seeded with RANDOMSEED

CONTAINS


! THIS SUBROUTINE DRAWS ALL THE RANDOM NUMBERS FOR A RECORD
SUBROUTINE RANDOM

INTEGER*4 :: J, K
REAL*8, DIMENSION(20) :: RAN_NUM


! DRAW 20 RANDOM NUMBERS
DO J = 1,20
	! DRAW A UNIFORM(0,1) RANDOM NUMBER
	RAN_NUM(J) = RANNUM(RANSEED_SEQ)
	print *, j, ": ", ran_num(j)
END DO




END SUBROUTINE RANDOM

SUBROUTINE INIT_RANDOM_NUMBER_GENERATOR
IMPLICIT NONE
INTEGER*4 :: J
DO J = 1,12
	RANDOMSTATUS(RANSEED_SEQ,J) = RANDOMSEED
END DO
END SUBROUTINE INIT_RANDOM_NUMBER_GENERATOR


FUNCTION RANNUM(SEQINDEX) RESULT(R)
IMPLICIT NONE
INTEGER*4, INTENT(IN) :: SEQINDEX
REAL*8 R

CALL RANDOM_SEED(PUT=RANDOMSTATUS(SEQINDEX, :))
CALL RANDOM_NUMBER(HARVEST=R)
CALL RANDOM_SEED(GET=RANDOMSTATUS(SEQINDEX, :))

END FUNCTION RANNUM

END MODULE RANDOM_MOD
